# Generated by Django 4.0.4 on 2022-05-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
